sonata_seo:
  encoding: 'UTF-8'
  page:
    title: 'Easy-trips - расскажи свою историю путешествия!'
    default: 'sonata.seo.page.default'
    metas:
      name:
  
        description: 'Создай свой личный блог путешествий и поделись своей историей | Easy-trips'
        robots: 'index, follow'