version: '3.1'
services:
#  mysql:
#    image: mysql:5.7
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    container_name: mysql_container
#    volumes:
#      - ./docker/data/db:/var/lib/mysql
#    ports:
#      - 3306:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  php:
    build: ./docker/php
    container_name: php_container
    volumes:
      - ${SYMFONY_APP}:/home/wwwroot
    environment:
      - maildev_host=civitta_maildev_container
    depends_on:
      - maildev
#      - mysql

  maildev:
    image: djfarrelly/maildev
    container_name: maildev_container
    ports:
      - 8001:80

  nginx:
    container_name: nginx_container
    build: ./docker/nginx
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d
      - ${SYMFONY_APP}:/home/wwwroot
    links:
      - php
    ports:
      - 80:80
      - 443:443